# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810c883718c8bb775df05268d3648ed61c3829b753cda594a08f22d39bf36fd746124ae019eeafc9dc0a7b0926bcf193d17888580c8941d84b67f4f52759a589

test:
  secret_key_base: e67256e990d67fd91e2731506e1b9d919573a556c3c8329d2bfc13b8c7049c7deb33b763bb7ea13d80ab9921d062269074a7566c315c805e5490129ad02d9c29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
